url: https://utilisable.github.io/uophysicsdemos/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

collections:
  demos:
    output: true
    name: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
