url: https://utilisable.github.io/uophysicsdemos/
plugins:
  - jekyll-relative-links
  - jekyll_picture_tag
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-minimal

collections:
  demos:
    output: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

picture:
  source: "assets/images/fullsize"
  output: "assets/images/generated"